apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-was-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
        - name: us-was-container
          image: 882157583740.dkr.ecr.ap-northeast-2.amazonaws.com/us-east-repository:9d2e092
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: us-was-alb-service
spec:
  selector:
    app: was
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: us-was-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: us-was-deploy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
